### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1 when getting block id in chunk by cords

### ISSUE THREAD

**Issue by Lennyss** [GeyserMC/MCProtocolLib#228] opened 2017-05-05 16:22 UTC
i try to use this methods to get block id:
    public static int getIdv2(double cx, double cy, double cz) {
        int x = (int) Math.floor(cx), y = (int) Math.floor(cy), z = (int) Math.floor(cz);
        Chunk chunk = getChunk(x / 16, y / 16, z / 16);
        return chunk.getBlocks().getBlock(x, y, z);
    }

    public static int getId(double x, double y, double z) {
        double cx = x / 16, cy = y / 16, cz = z / 16;
        Chunk c = getChunk((int) Math.floor(cx), (int) Math.floor(cy), (int) Math.floor(cz));
        int b = c.getBlocks().getBlock((int) x % 16, (int) y % 16, (int) z % 16);
        return b;
    }
where method getChunk()-> 
    public static Chunk getChunk(int x, int y, int z) {
        for (ChunkColumn cl : Main.chunkColumns) {
            if (cl.x == x && cl.z == z) {
                if (cl.chunks[y] == null || cl.chunks[y].getBlocks() == null) {
                    continue;
                }
                return cl.chunks[y];
            }
        }
        return null;
    }
and cl.chunks is create from packet ServerMultiChunkDataPacket and ServerChunkDataPacket
what i do wrong first method return indexOutOfounds -1 and second return ~-210?

**Comment by Steveice10** [comment] 2017-05-05 19:20
The first method, getIdv2, does not make sure the coordinates passed to getBlock are between 0 and 15 like the second one does. As for the return value, I'm not sure exactly how your chunk code is set up, but make sure you're not using the raw packed ID and data values.

**Comment by Lennyss** [comment] 2017-05-05 20:40
i will paste more code, First time I use packects in minecraft and it's a bit hard for me xD
in PacketReceivedEvent
if (event.getPacket() instanceof ServerChunkDataPacket) {
            ServerChunkDataPacket p = event.<ServerChunkDataPacket>getPacket();
            MinecraftBots.chunkColumns.add(new ChunkColumn(p.getX(), p.getZ(), p.getChunks()));
}
if (event.getPacket() instanceof ServerMultiChunkDataPacket) {
            for (int i = 0; i < event.<ServerMultiChunkDataPacket>getPacket().getColumns(); i++) {
                int chunkX = event.<ServerMultiChunkDataPacket>getPacket().getX(i);
                int chunkZ = event.<ServerMultiChunkDataPacket>getPacket().getZ(i);
                MinecraftBots.chunkColumns.add(
                        new ChunkColumn(chunkX, chunkZ, event.<ServerMultiChunkDataPacket>getPacket().getChunks(i)));
            }
}
ChunkColumn (im use a bit code from https://github.com/phase/PhaseBot)
https://pastebin.com/Jun5PVuC
and i think it is all :) 
and this is my stack when i use method getId()
java.lang.ArrayIndexOutOfBoundsException: -208
	at org.spacehq.mc.protocol.data.game.ShortArray3d.get(ShortArray3d.java:22)
	at org.spacehq.mc.protocol.data.game.ShortArray3d.getBlock(ShortArray3d.java:30)
	at chunks.ChunkColumn.getId(ChunkColumn.java:42)
line 42:         int b = c.getBlocks().getBlock((int) x % 16, (int) y % 16, (int) z % 16);

**Comment by Steveice10** [comment] 2017-05-05 21:30
Ahh, I think I might know what's going on. Make sure that if you're looking for a block at negative coordinates, the calculated chunk coordinates (0-15) do not end up negative.

**Comment by Lennyss** [comment] 2017-05-05 22:17
You're right
on negative cords
My Position: -2.5,66.0,38.5
this is chunk pos: -2 1 6 Should I use Math.abs? to change -2 to 2? is good idea?

**Comment by Steveice10** [comment] 2017-05-05 22:20
I would recommend using "& 15" instead of "% 16"

**Comment by Lennyss** [comment] 2017-05-05 22:28
when i change this:
        int b = c.getBlocks().getBlock((int) x % 16, (int) y % 16, (int) z % 16);
to:
        int b = c.getBlocks().getBlock((int) x & 15, (int) y & 15, (int) z & 15);
id on postive cords is good but on negative now return bad id f.e 
when stay on cobblestone return 0 
when stay on "podzol"return good id: 3
when stay on "green stained clay" (id: 159) return id:3

**Comment by phase** [comment] 2017-05-05 23:07
I was guessing you were using my code ;)

Are you account for block change packets? I had a hard time getting all of this working.

**Comment by Lennyss** [comment] 2017-05-05 23:15
@phase i don't understand your question but if you ask about seting block after get ServerMultiBlockChangePacket this packet, yes i do this with (your function)
https://pastebin.com/53P6js88
Btw. is any way to send pw to you about your bots?

**Comment by Steveice10** [comment] 2017-05-05 23:16
Try using ">> 4" instead of "/ 16" for the chunk coordinates as well.

**Comment by Lennyss** [comment] 2017-05-05 23:23
@Steveice10  when i change this /16 to >> 4
i have error: bad operand types for binary operator >>
        Chunk d = getChunk((int) Math.floor(x >> 4), (int) Math.floor(x >> 4), (int) Math.floor(x >> 4));

**Comment by Steveice10** [comment] 2017-05-05 23:25
Put the ">> 4" outside of floor, operating on the int result.

**Comment by Lennyss** [comment] 2017-05-05 23:35
@Steveice10  with this code:
        Chunk d = getChunk((int) Math.floor(cx) >> 4, (int) Math.floor(cy) >> 4, (int) Math.floor(cz) >> 4);
when bot stay on grass block i got id: 7 on negative cords

**Comment by Steveice10** [comment] 2017-05-05 23:37
Can you try inserting a print out of the chunk coordinates + block coordinates within the chunk and verify that they match up with the position of the block in question?

**Comment by Lennyss** [comment] 2017-05-05 23:50
@Steveice10  how can i do this? i try somethink like this:
        for (int i = 0; i < chunks.length; i++) {
            Chunk chunk = chunks[i];
            for (Short s : chunk.getBlocks().getData()) {
                System.out.println(x + " " + i + " " + z + " " + s);
            }
        }
but i don't have clue how to make this, i will check tomorrow answer now is too late for programing xD

**Comment by Steveice10** [comment] 2017-05-05 23:57
In getId, print the results of values like "(int) Math.floor(x >> 4)" and "(int) x & 15".

**Comment by Lennyss** [comment] 2017-05-06 10:32
@Steveice10  
X|Y|Z: -2.5 65.0 40.5 <- bots cords -1 on Y
X|Y|Z & 15: 14 1 8
X|Y|Z >>4 :  -1 4 2
Block ID: 0 <- but stand on cobblestone
X|Y|Z: 8.5 65.0 40.5
X|Y|Z & 15: 8 1 8
X|Y|Z >>4 :  0 4 2
Block ID: 0 <- but stand on cobblestone
when i change 
getChunk((int) Math.floor(x) >> 4, (int) Math.floor(y) >> 4, (int) Math.floor(z) >> 4);
to:
 Chunk c = getChunk((int) Math.floor(cx), (int) Math.floor(cy), (int) Math.floor(cz));
where cx is x/16;

X|Y|Z: 8.5 65.0 40.5
X|Y|Z & 15: 8 1 8
X|Y|Z / 16 :  0 4 2
Block ID: 4 <- correct value
 on negative:
X|Y|Z: -2.5 65.0 40.5
X|Y|Z & 15: 14 1 8
X|Y|Z >>4 :  -1 4 2
Block id: 0 <- stand on cobblestone :/

**Comment by Steveice10** [comment] 2017-05-06 15:05
One thing I can think if is that you should make sure that, if you receive another chunk packet containing a column, make sure to remove the existing column you have stored for those coordinates to avoid duplicates. Otherwise, I'm not sure what the problem is.

**Comment by Lennyss** [comment] 2017-05-06 16:24
@Steveice10 i start removing columns
if (event.getPacket() instanceof ServerChunkDataPacket) {
            ServerChunkDataPacket p = event.<ServerChunkDataPacket>getPacket();
            ChunkColumn old = ChunkColumn.getChunkColumnByCords(p.getX(), p.getZ());
            if (old != null) {
                System.out.println("removing old chunk column");
                MinecraftBots.chunkColumns.remove(old);
            }
            MinecraftBots.chunkColumns.add(new ChunkColumn(p.getX(), p.getZ(), p.getChunks()));
        }
like this but still id is wrong on negative cords;/

**Comment by Lennyss** [comment] 2017-05-11 17:19
@Steveice10 Have you any idea what i should do? or maybe you can write example code to check id block and add to examples in repo? i think many people can use this :)

**Comment by Steveice10** [comment] 2017-05-11 21:41
The thing is, you're using an outdated version of MCProtocolLib, so none of this would apply to the library as it is now. The chunk format is different now from how it used to be.

**Comment by Steveice10** [comment] 2017-06-10 18:41
Going to close this since it applies to an outdated library version.

**Closed as completed by Steveice10** 2017-06-10 18:41 UTC
