### ISSUE TITLE
Not loading SRV Records

### ISSUE THREAD

**Issue by phase** [GeyserMC/MCProtocolLib#85] opened 2015-04-05 02:53 UTC
Whilst trying to run your example code, the program just stalled. I added `println`s at various locations, only to find nothing was getting past `client.getSession().connect()`. I put in the correct values for the variables at the top, but I was unable to get the code working. [Here's the source code](https://github.com/phase/minekraft/blob/master/src/xyz/jadonfowler/minekraft/Minekraft.kt), but it's remade in Kotlin (a [Java version](https://github.com/CraftDevs/CraftClient) did the same thing).

**Comment by Lukario45** [comment] 2015-04-13 14:09
Is it possible that your host may be the issue? Try setting it to localhost or whatever your computers internal IP address is. For my software i tell the JVM to get the address but just typing your internal address should work

**Comment by phase** [comment] 2015-04-13 18:55
But if I only use my internal address, then it's useless. I've tried it with many different servers with the same result.

**Comment by Lukario45** [comment] 2015-04-14 10:51
When hosting a server you must use your computers internal ip address and you port forward a port through your router/modem. The host option is referring to that IP. You can't set that to a host that your computer does not have. Did you port forward with those other servers? After assigning your internal ip users must connect through your external ip, which can be found on sites like ipchicken, and your port. You can then redirect a domain or subdomain to your external IP address. If you have multiple routers connected to each other (maybe wired to wireless etc) then I think you need to port forward on both routers but I am not sure.

**Comment by Johni0702** [comment] 2015-04-14 12:09
If I recall correctly I've looked into this a week ago and it seems to be caused by some internal not handling `Proxy.NO_PROXY` correctly (it might even be caused by proxies in general; haven't tested that). Somewhere a `UnknownHostException` (or a similar exception) was thrown, silently caught, terminating the netty thread and leaving your main thread waiting for it indefinitely.

Using the `TcpSessionFactory` constructor without the proxy argument seemed to work as expected.

I haven't looked into it any further so I cannot tell where the actual problem lies nor how to fix it.

**Comment by phase** [comment] 2015-04-14 15:44
@Lukario45 I'm not hosting a server, I'm making a client.

@Johni0702 Awesome, I'll check that out later.

**Comment by phase** [comment] 2015-04-17 00:01
@Johni0702 Putting in no arguments didn't seem to fix the problem, it's still stalling.

**Comment by Johni0702** [comment] 2015-04-17 12:21
Ok, I've used the debugger once again. [This](https://i.johni0702.de/hm.png) is the exception swallowed somewhere in the code (using the java version of your code).

Taking a closer look it turns out that mc.openredstone.org uses SRV records to provide _minecraft at mort.openredstone.org:25569.
There is no A record for mc.openredstone.org itself which probably caused this exception to be thrown.

Using the resolved address for the hostname and port resulted in the client being disconnected by the server: "Disconnected: Login failed: Authentication service unavailable." but I assume that's a server problem as I also tried to connect to a local (Glowstone) server which worked completely as expected.

So from here I see two options:
- Implementing SRV support in the PacketLib or
- you implementing it yourself in your client

Either way there is still the issue of the exception being swallowed which has to be fixed in PacketLib. I suspect you could get this particular exception from the channel future [here](https://github.com/Steveice10/PacketLib/blob/master/src/main/java/org/spacehq/packetlib/tcp/TcpSession.java#L68) and would have to call the `exceptionCaught` method manually (though I haven't look into that) or maybe even rethow it.

**Comment by Steveice10** [comment] 2015-04-17 15:47
Does [these](https://github.com/Steveice10/PacketLib/commit/3d3ebad1f4428a534739db8c9ddee890b1b58d90) [commits](https://github.com/Steveice10/PacketLib/commit/3687891770efbf55c36d94bd9c6096e2e9821f91) improve the exception swallowing issue?

**Comment by Johni0702** [comment] 2015-04-17 16:35
@Steveice10 Yes they did. The exception is now printed to the console as expected. Thanks!

Edit: And it no longer causes stalling.

**Comment by Steveice10** [comment] 2015-04-17 17:52
Good to hear, exception handling had always been a bit iffy in PacketLib.

As the the SRV record thing, Java itself should already work fine with SRV records. Not sure why that would happen.

**Comment by Johni0702** [comment] 2015-04-17 19:19
I'm actually not sure whether Java has built-in SRV record support.
Either way the program would have to tell the [service](http://en.wikipedia.org/wiki/SRV_record#Record_format) name to Java at some point (which I didn't find, so I assumed it isn't supported).

Feel free to correct me, I haven't made use of SRV records from anything other than python so I might have missed something.

**Comment by Steveice10** [comment] 2015-04-17 19:43
If it didn't, that would be kind of strange. Minecraft itself supports SRV records, obviously, yet (unless I'm mistaken, it's been a while since I've checked) it doesn't have any special code for them.

**Comment by Johni0702** [comment] 2015-04-18 11:20
Ok, I've searched the decompiled minecraft source code and I believe I have found where minecraft looks up the SRV records.
Searching for strings such as "srv" or "_minecraft" produced no results. However searching for the default port (which minecraft must append to the domain name at some point) was successful. (class `bdd` in minecraft 1.8.4)
The decompiler I've been using ([JD](http://jd.benow.ca/)) failed to decompile one of the methods in that class and only dumped the bytecode of that method. Therefore it didn't resolve the string literals which caused all my searches to fail.

Minecraft forge with snapshot_nodoc_20141130 mcp mappings (and the IntelliJ decompiler) is able to decompile the method correctly. The corresponding class is `net.minecraft.client.multiplayer.ServerAddress` and the method used to resolve SRV records approximately looks like this:

```
try {
            Class.forName("com.sun.jndi.dns.DnsContextFactory");
            Hashtable<String, String> config = new Hashtable<>();
            config.put("java.naming.factory.initial", "com.sun.jndi.dns.DnsContextFactory");
            config.put("java.naming.provider.url", "dns:");
            config.put("com.sun.jndi.dns.timeout.retries", "1");
            String[] result = new InitialDirContext(config).getAttributes("_minecraft._tcp." + serverAddress, new String[]{"SRV"}).get("srv").get().toString().split(" ", 4);
            return new String[]{result[3], result[2]};
        } catch (Throwable t) {
            return new String[]{serverAddress, Integer.toString(25565)};
        }
```

**Comment by phase** [comment] 2015-05-30 11:48
MCProtocolLib definitely isn't loading SRV Records for Client.

**Comment by Steveice10** [comment] 2015-07-20 19:25
SRV record support has been implemented in PacketLib.

**Closed as completed by Steveice10** 2015-07-20 19:25 UTC
