### ISSUE TITLE
Issue with latest commit

### ISSUE THREAD

**Issue by lukeeey** [GeyserMC/MCProtocolLib#480] opened 2019-08-24 11:06 UTC
Somewhere with the latest commit i'm getting this error:
```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: data is marked non-null but is null
```

This was not present before this commit and the error message doesn't help me find the issue

**Comment by MatteCarra** [comment] 2019-08-24 14:02
I can't reproduce your problem sadly.
More details (for example how to reproduce the error) could help.

**Comment by lukeeey** [comment] 2019-08-24 14:10
I literally took my existing code that works and modified some getter methods to work with the new lombok-ified version and then i joined hypixel.

**Comment by MatteCarra** [comment] 2019-08-24 14:17
Well you have said 'last commit' and this is the last commit: b13592686b5bec42321ba7d55b2a5ca1a30cfb73
Have you tried to selectively undo commits until you find the coolprit?

I've replied to this issue because you said that latest commit ( b13592686b5bec42321ba7d55b2a5ca1a30cfb73 ) is causing you trouble, while it's running well for me.
I've not tried other lombok commits yet.

**Comment by lukeeey** [comment] 2019-08-24 14:30
I meant the second to latest commit as i thought it was the latest commit. The lombok update by steveice10

**Comment by Steveice10** [comment] 2019-08-24 16:05
Where are you getting that error from? Most internal errors should be passed to the disconnect event handlers, from which you can call getCause and print the stack trace.

**Comment by Steveice10** [comment] 2019-08-24 16:21
Should be fixed in https://github.com/Steveice10/MCProtocolLib/commit/fbef6f274fefcb13edfd37cf951f1faa0e99ac5b

Let me know if any other issues like this crop up.

**Closed as completed by Steveice10** 2019-08-24 16:21 UTC
